[Fix] NoSuchMethodError due to ontodriver-sesame bad dependencies
Workaround for java.lang.NoSuchMethodError: 'void org.eclipse.rdf4j.query.algebra.evaluation.EvaluationStrategyFactory.setTrackResultSize(boolean)' due to bad dependencies in ontodriver-sesame as described here :
https://github.com/kbss-cvut/jopa/issues/107