Fix version of org.eclipse.rdf4j package
Proper fix for java.lang.NoSuchMethodError: 'void org.eclipse.rdf4j.query.algebra.evaluation.EvaluationStrategyFactory.setTrackResultSize(boolean)' due to bad dependencies in ontodriver-sesame as described here :
https://github.com/kbss-cvut/jopa/issues/107